In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from 'C:\\Users\\Akhilesh Kumar\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
lst=[1,2,3]

In [4]:
type(lst)

list

In [5]:
np_array=numpy.array(lst)

In [6]:
np_array

array([1, 2, 3])

In [7]:
lst

[1, 2, 3]

In [8]:
lst=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np_array=numpy.array(lst)

In [10]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np_array.shape

(3, 3)

In [20]:
rand=numpy.random.randint(0,9)
print(rand)

8


In [23]:
numpy.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [24]:
numpy.mean(numpy.linspace(2,10,5))

6.0

In [25]:
numpy.sqrt(numpy.linspace(2,10,5))

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [26]:
array=numpy.linspace(2,10,7)

In [27]:
array

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [28]:
array+2

array([ 4.        ,  5.33333333,  6.66666667,  8.        ,  9.33333333,
       10.66666667, 12.        ])

In [29]:
array/2

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [30]:
lst=[1,2,3]

In [31]:
for i in lst:
    temp=i+2
    print(temp)

3
4
5


In [32]:
temp_lst=[]
for i in lst:
    temp=i+2
    temp_lst.append(temp)

In [33]:
temp_lst

[3, 4, 5]